apiVersion: v1
stringData:
  # KeycloakDS
  KEYCLOAKDS_POOL_NAME: 'KeycloakDS'
  KEYCLOAKDS_JNDI_NAME: 'java:jboss/datasources/KeycloakDS'
  KEYCLOAKDS_CONNECTION_URL: >-
    jdbc:oracle:thin:@xyz.com.br:1521:sso
  KEYCLOAKDS_MIN_POOL_SIZE: '5'
  KEYCLOAKDS_MAX_POOL_SIZE: '20'
  KEYCLOAKDS_USER_NAME: 'user'
  KEYCLOAKDS_PASSWORD: 'pass'
kind: Secret
metadata:
  name: keycloak-datasource
type: Opaque
